"""
analysis/01_data_cleaning.py

Loads each raw NFCS State-by-State wave (2018, 2021, 2024), applies the
shared recoding logic in utils.py, and writes:

  data/cleaned/nfcs_2018_cleaned.csv
  data/cleaned/nfcs_2021_cleaned.csv
  data/cleaned/nfcs_2024_cleaned.csv
  data/cleaned/nfcs_pooled_2018_2021_2024.csv   (all three waves stacked)
  docs/cleaning_log.md                           (auto-generated, per-variable
                                                    missingness by wave)

Run this first. Every downstream script reads from data/cleaned/, never
from data/raw/ directly -- that boundary is intentional: raw NFCS exports
should never be edited or filtered in place, and recoding logic should
exist in exactly one place (utils.load_and_recode_wave).
"""

import os
import sys
import pandas as pd

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import utils


def write_cleaning_log(log_rows: list, path: str) -> None:
    log_df = pd.DataFrame(log_rows)
    lines = [
        "# Cleaning Log — NFCS State-by-State Survey (2018, 2021, 2024)",
        "",
        "Auto-generated by `analysis/01_data_cleaning.py`. Do not edit by hand —",
        "regenerate by re-running the script if source data or recoding changes.",
        "",
        "For each analytic variable, this shows how many respondents in each wave",
        "had a valid (non-missing) value after recoding, and how many were dropped",
        "as missing (either genuinely not asked due to survey skip logic, or",
        "'Don't know' / 'Refused' responses, coded 98/99 in the raw NFCS files).",
        "",
    ]
    for wave in sorted(log_df["wave"].unique()):
        wdf = log_df[log_df["wave"] == wave]
        n_total = None
        lines.append(f"## Wave {wave}")
        lines.append("")
        lines.append("| Variable | Source column | N valid | N missing | % missing |")
        lines.append("|---|---|---|---|---|")
        for _, row in wdf.iterrows():
            lines.append(
                f"| `{row['variable']}` | `{row['source_column']}` | "
                f"{row['n_valid']:,} | {row['n_missing']:,} | {row['pct_missing']}% |"
            )
        lines.append("")

    lines.append("## Notes")
    lines.append("")
    lines.append("- `female` is 100% missing in 2018: the gender item (A50A) was not")
    lines.append("  collected in that wave's questionnaire. Gender is dropped entirely from")
    lines.append("  all pooled/by-wave models for cross-wave consistency (see")
    lines.append("  `docs/analytical_decisions.md`).")
    lines.append("- Credit-card items (`pays_cc_full`, `revolves_cc_balance`) show higher")
    lines.append("  missingness than other variables because of survey skip logic: they are")
    lines.append("  only asked of respondents who report having a credit card.")
    lines.append("- 'Missing' here always means genuinely absent information (skip logic, or")
    lines.append("  don't-know/refused) — never imputed or estimated.")

    with open(path, "w") as f:
        f.write("\n".join(lines))


if __name__ == "__main__":
    log_rows: list = []
    cleaned_frames = {}

    for wave, cfg in utils.WAVE_PATHS.items():
        print(f"Loading and recoding wave {wave} from {cfg['csv']} ...")
        df = utils.load_and_recode_wave(
            cfg["csv"], cfg["income_col"], cfg["has_gender"], wave=wave, log_rows=log_rows
        )
        cleaned_frames[wave] = df
        out_path = os.path.join(utils.CLEANED_DIR, f"nfcs_{wave}_cleaned.csv")
        df.to_csv(out_path, index=False)
        print(f"  -> {len(df):,} rows written to {out_path}")

    pooled = pd.concat(cleaned_frames.values(), ignore_index=True)
    pooled_path = os.path.join(utils.CLEANED_DIR, "nfcs_pooled_2018_2021_2024.csv")
    pooled.to_csv(pooled_path, index=False)
    print(f"\nPooled file: {len(pooled):,} rows written to {pooled_path}")

    log_path = os.path.join(utils.DOCS_DIR, "cleaning_log.md")
    write_cleaning_log(log_rows, log_path)
    print(f"Cleaning log written to {log_path}")
